apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx  # 네임스페이스 추가
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: acrpkj.azurecr.io/pkj1:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service  
  namespace: nginx  # 네임스페이스 추가
spec:
  type: LoadBalancer
  selector:    
    app: nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
